### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by skip405** [vixnguyen/timezone-select#3]
Hello, writing to enquire if there are plans to update devDependencies and regular dependencies for this project. E.g. bundled `react-select` which is listed as a dependency is of version `3.1.0` while the latest available is `5.4.0`.

**Comment by vixnguyen** [comment]
Hi @skip405,
Sorry for the late response. We will update dependences to the latest version soon.
FYI, I have a plan to have a breaking change to this package
- Will remove all React related(including react-select) code from this package. It means, this package just a regular JavaScript package, like its name `timezone-select-js`.
- Create a new package that support for react, the new package will use `timezone-select-js` as a dependence.

**Comment by skip405** [comment]
Hi @vixnguyen. Thanks for the update. In fact, I did something similar for my own project :) Closing the issue as irrelevant, will keep an eye on your updates.

**Comment by vixnguyen** [comment]
@skip405 I really appreciate your attention 💯
